version: "3"
services:
  code-server:
    image: linuxserver/code-server:latest
    container_name: code-server
    restart: unless-stopped
    ports:
      - 2048:8443
    secrets:  # 传入secrets到/run/secrets/目录下
      - code_server_password
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      # - PASSWORD=password   
      # - SUDO_PASSWORD=password                     # 用该密码获取sudo
      - HASHED_PASSWORD=/run/secrets/code_server_password
      - SUDO_PASSWORD_HASH=/run/secrets/code_server_password
      # - PROXY_DOMAIN=code-server.my.domain         # 反向代理设置
      # - CODE_SERVER_CONFIG=/config/config.yaml
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - /etc/localtime:/etc/localtime
      - /soft/code-server/config:/config/

# 使用secrets
secrets:
  code_server_password:
    external: true
