version: "3"
services:
  code-server:
    image: linuxserver/code-server:latest
    container_name: code-server
    restart: unless-stopped
    ports:
      - 2048:8443
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      # - PASSWORD=password  
      - FILE__HASHED_PASSWORD=/config/passwd
      # - SUDO_PASSWORD=password                     # 用该密码获取sudo
      - FILE__SUDO_PASSWORD_HASH=/config/passwd
      # - PROXY_DOMAIN=code-server.my.domain         # 反向代理设置
      # - CODE_SERVER_CONFIG=/config/config.yaml
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - /etc/localtime:/etc/localtime
      - /soft/code-server/config:/config/
