version: "3.1"
services:
  code-server:
    image: koray2021/code-server:4.14.1-arm64
    container_name: code-server
    hostname: code-server
    restart: always
    ports:
      - 2048:8443
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - PASSWORD=${password}
      - SUDO_PASSWORD=${password}              # 用该密码获取sudo
      # - HASHED_PASSWORD=${password}          # hash与config文件配置密码都无效
      # - SUDO_PASSWORD_HASH=${password}
      # - PROXY_DOMAIN=code-server.my.domain   # 反向代理设置
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - /etc/localtime:/etc/localtime
      - ./config:/config
